In [2]:
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cpu


In [3]:
import pandas as pd
from torch.utils.data import Dataset
import os
import torchaudio

class My_Dataset(Dataset):

    def __init__(self, csv_file, root_dir, set_number):
        """
        Arguments:
            csv_file (string): Path to the csv file with annotations.
            root_dir (string): Directory with all the audio files.
            set_number (int): Set number to filter the samples.
        """
        self.data = pd.read_csv(csv_file)
        self.root_dir = root_dir
        self.set_number = set_number
        self.filtered_indices = self.filter()

    def __len__(self):
        return len(self.filtered_indices)

    def filter(self):
        filtered_indices = []
        for idx in range(len(self.data)):
            set_value = int(self.data.iloc[idx, 1])
            if set_value == self.set_number:
                filtered_indices.append(idx)
        return filtered_indices

    def __getitem__(self, idx):
        idx = self.filtered_indices[idx]
        file = os.path.join(self.root_dir, self.data.iloc[idx, 0])
        class_label = int(self.data.iloc[idx, 2])
        waveform, _ = torchaudio.load(file)
        return waveform, class_label

csv_file = 'dataset.csv'
root_dir = 'Inregistrari'
train_dataset = My_Dataset(csv_file, root_dir, 0)
test_dataset = My_Dataset(csv_file, root_dir, 1)
valid_dataset = My_Dataset(csv_file, root_dir, 2)
print(train_dataset[0])
print(test_dataset[0])
print(valid_dataset[0])


(tensor([[-0.0282, -0.0244, -0.0236,  ...,  0.0104,  0.0114,  0.0126]]), 3)
(tensor([[ 9.1553e-05, -2.7466e-04, -9.1553e-04,  ..., -3.9673e-04,
         -4.8828e-04, -4.5776e-04]]), 2)
(tensor([[-0.0032, -0.0017, -0.0019,  ...,  0.0024,  0.0081,  0.0065]]), 3)


In [4]:
import matplotlib.pyplot as plt
import os
from torch.utils.data import DataLoader
# from torchvision import datasets
from torchvision.transforms import ToTensor
plt.style.use('ggplot')

batch_size = 64
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=0, pin_memory=True)
valid_loader = DataLoader(valid_dataset, batch_size=batch_size, shuffle=False, num_workers=0, pin_memory=True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=0, pin_memory=True)

for batch, (X, y) in enumerate(train_loader):
    print(X.shape, y.shape)
    if batch == 3:
        break

# Print class distribution
class_counts = train_dataset.data.iloc[train_dataset.filtered_indices, 2].value_counts()
print("Class distribution in training set:", class_counts)

torch.Size([64, 1, 16000]) torch.Size([64])
torch.Size([64, 1, 16000]) torch.Size([64])
torch.Size([64, 1, 16000]) torch.Size([64])
torch.Size([64, 1, 16000]) torch.Size([64])
Class distribution in training set: class
4    60
0    60
2    59
5    57
3    55
1    45
Name: count, dtype: int64


In [5]:
classes = ['start', 'stop', 'home', 'pick_up', 'approach', 'free']

In [6]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader
from tqdm import tqdm

class SimplifiedWaveNet(nn.Module):
    def __init__(self, num_classes, num_channels=128, num_layers=3, num_filters=16, dilation_rates=None):
        super(SimplifiedWaveNet, self).__init__()
        
        if dilation_rates is None:
            dilation_rates = [2**i for i in range(num_layers)]
        
        self.num_layers = num_layers
        self.num_filters = num_filters
        self.dilation_rates = dilation_rates
        
        self.init_conv = nn.Conv1d(num_channels, num_filters, kernel_size=1)
        
        self.dilated_layers = nn.ModuleList()
        for dilation_rate in dilation_rates:
            self.dilated_layers.append(nn.Sequential(
                nn.Conv1d(num_filters, num_filters, kernel_size=2, stride=1,
                          dilation=dilation_rate, padding=dilation_rate),
                nn.ReLU(inplace=True)
            ))
        
        self.final_conv = nn.Conv1d(num_filters, num_classes, kernel_size=1)
    
    def forward(self, x):
        x = self.init_conv(x)
        
        skip_connections = []
        for layer in self.dilated_layers:
            x = layer(x)
            skip_connections.append(x)
        
        min_size = min([s.size(2) for s in skip_connections])
        adjusted_skip_connections = [s[:, :, :min_size] for s in skip_connections]
        
        x = sum(adjusted_skip_connections)
        x = F.relu(x)
        x = self.final_conv(x)
        
        x = F.adaptive_avg_pool1d(x, 1).squeeze(-1)
        
        return x

def get_simplified_wavenet(num_classes, num_channels=128, num_layers=3, num_filters=16, dilation_rates=None, device='cpu'):
    model = SimplifiedWaveNet(num_classes, num_channels, num_layers, num_filters, dilation_rates)
    return model.to(device)

# Example usage with the correct number of input channels:
num_input_channels = 128  # Adjust as needed
device = 'cuda' if torch.cuda.is_available() else 'cpu'
model = get_simplified_wavenet(num_classes=6, num_channels=num_input_channels, num_layers=3, num_filters=16, device=device)
print(model)

SimplifiedWaveNet(
  (init_conv): Conv1d(128, 16, kernel_size=(1,), stride=(1,))
  (dilated_layers): ModuleList(
    (0): Sequential(
      (0): Conv1d(16, 16, kernel_size=(2,), stride=(1,), padding=(1,))
      (1): ReLU(inplace=True)
    )
    (1): Sequential(
      (0): Conv1d(16, 16, kernel_size=(2,), stride=(1,), padding=(2,), dilation=(2,))
      (1): ReLU(inplace=True)
    )
    (2): Sequential(
      (0): Conv1d(16, 16, kernel_size=(2,), stride=(1,), padding=(4,), dilation=(4,))
      (1): ReLU(inplace=True)
    )
  )
  (final_conv): Conv1d(16, 6, kernel_size=(1,), stride=(1,))
)


In [7]:
import  torch.optim as optim
# Define the optimizer and loss function
optimizer = optim.Adam(model.parameters(), lr=0.0001)  # Reduced learning rate
criterion = nn.CrossEntropyLoss()

In [8]:
train_losses = []
train_accuracies = []

# Training function
def train(model, device, train_loader, optimizer, epoch, log_interval, scheduler):
    model.train()
    running_loss = 0.0
    correct = 0
    for batch_idx, (data, target) in enumerate(train_loader):
        data, target = data.to(device), target.to(device)
        optimizer.zero_grad()
        data = data.squeeze(1)  # Remove channel dimension
        output = model(data)
        loss = criterion(output, target)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()
        pred = output.argmax(dim=1, keepdim=True)
        correct += pred.eq(target.view_as(pred)).sum().item()
        if batch_idx % log_interval == 0:
            print(f'Train Epoch: {epoch} [{batch_idx * len(data)}/{len(train_loader.dataset)} ({100. * batch_idx / len(train_loader):.0f}%)]\tLoss: {loss.item():.6f}')
    avg_loss = running_loss / len(train_loader)
    accuracy = 100. * correct / len(train_loader.dataset)
    train_losses.append(avg_loss)
    train_accuracies.append(accuracy)
    scheduler.step()

In [45]:
def number_of_correct(pred, target):
    return pred.squeeze().eq(target).sum().item()

def get_likely_index(tensor):
    return tensor.argmax(dim=-1)

test_losses = []
test_accuracies = []
all_preds = []
all_targets = []

# Testing function
def test(model, device, test_loader):
    model.eval()
    test_loss = 0.0
    correct = 0
    
    with torch.no_grad():
        for data, target in test_loader:
            data, target = data.to(device), target.to(device)
            # data = data.squeeze(1)  # Remove channel dimension
            output = model(data)
            loss = criterion(output, target)
            test_loss += loss.item() * data.size(0)  # Accumulate the loss
            pred = output.argmax(dim=1, keepdim=True)
            correct += pred.eq(target.view_as(pred)).sum().item()
            all_preds.extend(pred.cpu().numpy())
            all_targets.extend(target.cpu().numpy())

    avg_test_loss = test_loss / len(test_loader.dataset)  # Calculate average loss
    accuracy = 100. * correct / len(test_loader.dataset)
    test_losses.append(avg_test_loss)
    test_accuracies.append(accuracy)
    print(f'\nTest set: Average loss: {avg_test_loss:.4f}, Accuracy: {correct}/{len(test_loader.dataset)} ({accuracy:.0f}%)\n')


In [10]:
import torch
from torch import optim
from tqdm import tqdm

# Assuming model, device, train_loader, test_loader, optimizer are defined
# Assuming train and test functions are defined

n_epoch = 150
log_interval = 20

# Example of setting up a scheduler
scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=10, gamma=0.5)

with tqdm(total=n_epoch) as pbar:
    for epoch in range(1, n_epoch + 1):
        train(model, device, train_loader, optimizer, epoch, log_interval, scheduler)
        test(model, device, test_loader)
        torch.save(model.state_dict(), 'wavenet_command.pt')
        scheduler.step()  # Update the learning rate
        pbar.update(1)

  0%|          | 0/150 [00:00<?, ?it/s]


RuntimeError: Given groups=1, weight of size [16, 128, 1], expected input[1, 64, 16000] to have 128 channels, but got 64 channels instead

In [46]:
import torch
import pandas as pd
from torch.utils.data import Dataset
import os
import torchaudio

class My_Dataset(Dataset):
    def __init__(self, csv_file, root_dir, set_number):
        self.data = pd.read_csv(csv_file)
        self.root_dir = root_dir
        self.set_number = set_number
        self.filtered_indices = self.filter()

    def __len__(self):
        return len(self.filtered_indices)

    def filter(self):
        filtered_indices = []
        for idx in range(len(self.data)):
            set_value = int(self.data.iloc[idx, 1])
            if set_value == self.set_number:
                filtered_indices.append(idx)
        return filtered_indices

    def __getitem__(self, idx):
        idx = self.filtered_indices[idx]
        file = os.path.join(self.root_dir, self.data.iloc[idx, 0])
        class_label = int(self.data.iloc[idx, 2])
        waveform, _ = torchaudio.load(file)
        # Normalize the waveform
        waveform = (waveform - waveform.mean()) / waveform.std()
        # if waveform.shape[0] != num_input_channels:
        #     waveform = waveform.repeat(num_input_channels // waveform.shape[0], 1)
        return waveform, class_label

csv_file = 'dataset.csv'
root_dir = 'Inregistrari'
num_input_channels = 128  # Ensure this matches the expected input channels for the model

train_dataset = My_Dataset(csv_file, root_dir, 0)
test_dataset = My_Dataset(csv_file, root_dir, 1)
valid_dataset = My_Dataset(csv_file, root_dir, 2)



import torch.nn as nn
import torch.nn.functional as F

class SimplifiedWaveNet(nn.Module):
    def __init__(self, num_classes, num_channels=1, num_layers=4, num_filters=8, dilation_rates=None):
        super(SimplifiedWaveNet, self).__init__()
        self.num_layers = num_layers
        
        self.init_conv = nn.Conv1d(num_channels, num_filters, kernel_size=1)

        self.conv1 = nn.Conv1d(num_filters, num_filters * 2, kernel_size=3, padding=1, dilation=2)
        self.conv2 = nn.Conv1d(num_filters * 2, num_filters * 4, kernel_size=3, padding=2, dilation=4)
        self.conv3 = nn.Conv1d(num_filters * 4, num_filters * 8, kernel_size=3, padding=4, dilation=8)
        self.conv4 = nn.Conv1d(num_filters * 8, num_filters * 16, kernel_size=3, padding=8, dilation=16)

        self.pool = nn.MaxPool1d(4)

        self.final_conv = nn.Conv1d(256, 128, kernel_size=1)
        self.linear = nn.Linear(128 * 57 * 1, 256)
        self.linear2 = nn.Linear(256, num_classes)

    def forward(self, x):
        x = self.init_conv(x)
        x1 = self.pool(F.relu(self.conv1(x)))
        x2 = self.pool(F.relu(self.conv2(x1)))
        x3 = self.pool(F.relu(self.conv3(x2)))
        x4 = self.pool(F.relu(self.conv4(x3)))
        x5 = self.final_conv(x4)
        # print(x4.shape)
        x5 = x5.view(x5.size(0), -1)
        x6 = F.relu(self.linear(x5))
        x7 = self.linear2(x6)
        return x7



def get_simplified_wavenet(num_classes, num_channels=1, num_layers=3, num_filters=16, dilation_rates=None, device='cpu'):
    model = SimplifiedWaveNet(num_classes, num_channels, num_layers, num_filters, dilation_rates)
    return model.to(device)

model=get_simplified_wavenet(6)



#print the number of trainable parameters
def count_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)

nr = count_parameters(model)
print(f'The model has {nr:,} trainable parameters')
num_input_channels = 128  # Adju


import torch.optim as optim
from torch.utils.data import DataLoader
from tqdm import tqdm

batch_size = 64
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=0, pin_memory=True)
valid_loader = DataLoader(valid_dataset, batch_size=batch_size, shuffle=False, num_workers=0, pin_memory=True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=0, pin_memory=True)

    

optimizer = optim.Adam(model.parameters(), lr=0.001)  # Increased learning rate
criterion = nn.CrossEntropyLoss()

train_losses = []
train_accuracies = []
test_losses = []
test_accuracies = []
all_preds = []
all_targets = []

def train(model, device, train_loader, optimizer, epoch, log_interval, scheduler):
    model.train()
    running_loss = 0.0
    correct = 0
    for batch_idx, (data, target) in enumerate(train_loader):
        data, target = data.to(device), target.to(device)
        optimizer.zero_grad()
        # data = data.squeeze(1)  # Remove channel dimension

        # print(data.shape, target.shape)


        output = model(data)
        loss = criterion(output, target)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()
        pred = output.argmax(dim=1, keepdim=True)
        correct += pred.eq(target.view_as(pred)).sum().item()
        if batch_idx % log_interval == 0:
            print(f'Train Epoch: {epoch} [{batch_idx * len(data)}/{len(train_loader.dataset)} ({100. * batch_idx / len(train_loader):.0f}%)]\tLoss: {loss.item():.6f}')
    avg_loss = running_loss / len(train_loader)
    accuracy = 100. * correct / len(train_loader.dataset)
    train_losses.append(avg_loss)
    train_accuracies.append(accuracy)
    scheduler.step()
    print(f'Train Epoch: {epoch}\tAverage Loss: {avg_loss:.6f}\tAccuracy: {accuracy:.2f}%')


n_epoch = 150
log_interval = 20

scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=10, gamma=0.5)

with tqdm(total=n_epoch) as pbar:
    for epoch in range(1, n_epoch + 1):
        train(model, device, train_loader, optimizer, epoch, log_interval, scheduler)
        test(model, device, test_loader)
        torch.save(model.state_dict(), 'wavenet_command.pt')
        scheduler.step()  # Update the learning rate
        pbar.update(1)



The model has 2,033,542 trainable parameters


  0%|          | 0/150 [00:00<?, ?it/s]

Train Epoch: 1 [0/336 (0%)]	Loss: 1.795812
Train Epoch: 1	Average Loss: 1.813363	Accuracy: 14.58%


  1%|          | 1/150 [00:03<09:51,  3.97s/it]


Test set: Average loss: 1.8005, Accuracy: 12/96 (12%)

Train Epoch: 2 [0/336 (0%)]	Loss: 1.776709
Train Epoch: 2	Average Loss: 1.783729	Accuracy: 17.26%


  1%|▏         | 2/150 [00:07<09:29,  3.85s/it]


Test set: Average loss: 1.7961, Accuracy: 20/96 (21%)

Train Epoch: 3 [0/336 (0%)]	Loss: 1.742825
Train Epoch: 3	Average Loss: 1.741670	Accuracy: 30.65%


  2%|▏         | 3/150 [00:11<09:20,  3.81s/it]


Test set: Average loss: 1.7207, Accuracy: 32/96 (33%)

Train Epoch: 4 [0/336 (0%)]	Loss: 1.694700
Train Epoch: 4	Average Loss: 1.628575	Accuracy: 36.31%


  3%|▎         | 4/150 [00:15<09:19,  3.83s/it]


Test set: Average loss: 1.8101, Accuracy: 23/96 (24%)

Train Epoch: 5 [0/336 (0%)]	Loss: 1.622796
Train Epoch: 5	Average Loss: 1.472799	Accuracy: 45.24%


  3%|▎         | 5/150 [00:19<09:15,  3.83s/it]


Test set: Average loss: 1.4015, Accuracy: 45/96 (47%)

Train Epoch: 6 [0/336 (0%)]	Loss: 1.202370
Train Epoch: 6	Average Loss: 1.172192	Accuracy: 55.95%


  4%|▍         | 6/150 [00:22<09:08,  3.81s/it]


Test set: Average loss: 1.2455, Accuracy: 49/96 (51%)

Train Epoch: 7 [0/336 (0%)]	Loss: 1.015187
Train Epoch: 7	Average Loss: 0.887905	Accuracy: 72.62%


  5%|▍         | 7/150 [00:26<09:04,  3.81s/it]


Test set: Average loss: 1.3000, Accuracy: 47/96 (49%)

Train Epoch: 8 [0/336 (0%)]	Loss: 0.780526
Train Epoch: 8	Average Loss: 0.732422	Accuracy: 74.40%


  5%|▌         | 8/150 [00:30<08:58,  3.79s/it]


Test set: Average loss: 1.0804, Accuracy: 57/96 (59%)

Train Epoch: 9 [0/336 (0%)]	Loss: 0.588676
Train Epoch: 9	Average Loss: 0.542485	Accuracy: 79.46%


  6%|▌         | 9/150 [00:34<08:58,  3.82s/it]


Test set: Average loss: 1.1875, Accuracy: 56/96 (58%)

Train Epoch: 10 [0/336 (0%)]	Loss: 0.541437
Train Epoch: 10	Average Loss: 0.431883	Accuracy: 82.74%


  7%|▋         | 10/150 [00:38<08:54,  3.82s/it]


Test set: Average loss: 0.7329, Accuracy: 70/96 (73%)

Train Epoch: 11 [0/336 (0%)]	Loss: 0.287528
Train Epoch: 11	Average Loss: 0.357254	Accuracy: 86.90%


  7%|▋         | 11/150 [00:42<09:00,  3.89s/it]


Test set: Average loss: 0.7642, Accuracy: 74/96 (77%)

Train Epoch: 12 [0/336 (0%)]	Loss: 0.346369
Train Epoch: 12	Average Loss: 0.284541	Accuracy: 91.07%


  8%|▊         | 12/150 [00:46<09:02,  3.93s/it]


Test set: Average loss: 0.7254, Accuracy: 73/96 (76%)

Train Epoch: 13 [0/336 (0%)]	Loss: 0.269358
Train Epoch: 13	Average Loss: 0.254212	Accuracy: 92.56%


  9%|▊         | 13/150 [00:51<09:31,  4.17s/it]


Test set: Average loss: 0.7316, Accuracy: 75/96 (78%)

Train Epoch: 14 [0/336 (0%)]	Loss: 0.173580
Train Epoch: 14	Average Loss: 0.200192	Accuracy: 93.15%


  9%|▉         | 14/150 [00:55<09:46,  4.31s/it]


Test set: Average loss: 0.8200, Accuracy: 75/96 (78%)

Train Epoch: 15 [0/336 (0%)]	Loss: 0.264366
Train Epoch: 15	Average Loss: 0.187320	Accuracy: 93.75%


 10%|█         | 15/150 [00:59<09:39,  4.29s/it]


Test set: Average loss: 0.7406, Accuracy: 73/96 (76%)

Train Epoch: 16 [0/336 (0%)]	Loss: 0.191603
Train Epoch: 16	Average Loss: 0.147002	Accuracy: 95.83%


 11%|█         | 16/150 [01:03<09:25,  4.22s/it]


Test set: Average loss: 0.7723, Accuracy: 78/96 (81%)

Train Epoch: 17 [0/336 (0%)]	Loss: 0.135908
Train Epoch: 17	Average Loss: 0.135252	Accuracy: 96.13%


 11%|█▏        | 17/150 [01:08<09:18,  4.20s/it]


Test set: Average loss: 0.7387, Accuracy: 77/96 (80%)

Train Epoch: 18 [0/336 (0%)]	Loss: 0.137796
Train Epoch: 18	Average Loss: 0.111929	Accuracy: 98.81%


 12%|█▏        | 18/150 [01:12<09:16,  4.22s/it]


Test set: Average loss: 0.7329, Accuracy: 77/96 (80%)

Train Epoch: 19 [0/336 (0%)]	Loss: 0.113412
Train Epoch: 19	Average Loss: 0.104124	Accuracy: 98.21%


 13%|█▎        | 19/150 [01:16<09:02,  4.14s/it]


Test set: Average loss: 0.7551, Accuracy: 78/96 (81%)

Train Epoch: 20 [0/336 (0%)]	Loss: 0.063392
Train Epoch: 20	Average Loss: 0.092134	Accuracy: 98.81%


 13%|█▎        | 20/150 [01:20<09:08,  4.22s/it]


Test set: Average loss: 0.7472, Accuracy: 78/96 (81%)

Train Epoch: 21 [0/336 (0%)]	Loss: 0.116526
Train Epoch: 21	Average Loss: 0.096422	Accuracy: 98.51%


 14%|█▍        | 21/150 [01:24<08:40,  4.04s/it]


Test set: Average loss: 0.7535, Accuracy: 78/96 (81%)

Train Epoch: 22 [0/336 (0%)]	Loss: 0.063329
Train Epoch: 22	Average Loss: 0.085638	Accuracy: 99.40%


 15%|█▍        | 22/150 [01:28<08:23,  3.93s/it]


Test set: Average loss: 0.7782, Accuracy: 78/96 (81%)

Train Epoch: 23 [0/336 (0%)]	Loss: 0.066321
Train Epoch: 23	Average Loss: 0.079789	Accuracy: 99.11%


 15%|█▌        | 23/150 [01:31<08:13,  3.89s/it]


Test set: Average loss: 0.7549, Accuracy: 78/96 (81%)

Train Epoch: 24 [0/336 (0%)]	Loss: 0.101929
Train Epoch: 24	Average Loss: 0.083907	Accuracy: 99.11%


 16%|█▌        | 24/150 [01:35<08:06,  3.86s/it]


Test set: Average loss: 0.7636, Accuracy: 78/96 (81%)

Train Epoch: 25 [0/336 (0%)]	Loss: 0.106244
Train Epoch: 25	Average Loss: 0.081044	Accuracy: 98.81%


 17%|█▋        | 25/150 [01:39<07:59,  3.83s/it]


Test set: Average loss: 0.7829, Accuracy: 78/96 (81%)

Train Epoch: 26 [0/336 (0%)]	Loss: 0.065454
Train Epoch: 26	Average Loss: 0.068208	Accuracy: 99.70%


 17%|█▋        | 26/150 [01:43<08:07,  3.93s/it]


Test set: Average loss: 0.7728, Accuracy: 78/96 (81%)

Train Epoch: 27 [0/336 (0%)]	Loss: 0.065398
Train Epoch: 27	Average Loss: 0.065510	Accuracy: 99.70%


 18%|█▊        | 27/150 [01:49<09:21,  4.56s/it]


Test set: Average loss: 0.7695, Accuracy: 78/96 (81%)

Train Epoch: 28 [0/336 (0%)]	Loss: 0.065031
Train Epoch: 28	Average Loss: 0.069303	Accuracy: 99.11%


 19%|█▊        | 28/150 [01:54<09:18,  4.58s/it]


Test set: Average loss: 0.7734, Accuracy: 78/96 (81%)

Train Epoch: 29 [0/336 (0%)]	Loss: 0.055739
Train Epoch: 29	Average Loss: 0.059954	Accuracy: 99.40%


 19%|█▉        | 29/150 [01:58<08:56,  4.43s/it]


Test set: Average loss: 0.7798, Accuracy: 78/96 (81%)

Train Epoch: 30 [0/336 (0%)]	Loss: 0.074495
Train Epoch: 30	Average Loss: 0.059726	Accuracy: 99.70%


 20%|██        | 30/150 [02:02<08:55,  4.46s/it]


Test set: Average loss: 0.7849, Accuracy: 78/96 (81%)

Train Epoch: 31 [0/336 (0%)]	Loss: 0.068780
Train Epoch: 31	Average Loss: 0.060365	Accuracy: 100.00%


 21%|██        | 31/150 [02:07<08:52,  4.48s/it]


Test set: Average loss: 0.7868, Accuracy: 78/96 (81%)

Train Epoch: 32 [0/336 (0%)]	Loss: 0.059496
Train Epoch: 32	Average Loss: 0.059754	Accuracy: 99.70%


 21%|██▏       | 32/150 [02:12<08:56,  4.55s/it]


Test set: Average loss: 0.7860, Accuracy: 78/96 (81%)

Train Epoch: 33 [0/336 (0%)]	Loss: 0.055637
Train Epoch: 33	Average Loss: 0.063720	Accuracy: 99.70%


 22%|██▏       | 33/150 [02:16<09:02,  4.63s/it]


Test set: Average loss: 0.7865, Accuracy: 78/96 (81%)

Train Epoch: 34 [0/336 (0%)]	Loss: 0.053213
Train Epoch: 34	Average Loss: 0.058217	Accuracy: 100.00%


 23%|██▎       | 34/150 [02:21<09:09,  4.74s/it]


Test set: Average loss: 0.7886, Accuracy: 78/96 (81%)

Train Epoch: 35 [0/336 (0%)]	Loss: 0.065351
Train Epoch: 35	Average Loss: 0.057886	Accuracy: 100.00%


 23%|██▎       | 35/150 [02:26<09:10,  4.79s/it]


Test set: Average loss: 0.7910, Accuracy: 78/96 (81%)

Train Epoch: 36 [0/336 (0%)]	Loss: 0.044932
Train Epoch: 36	Average Loss: 0.053393	Accuracy: 100.00%


 24%|██▍       | 36/150 [02:31<09:01,  4.75s/it]


Test set: Average loss: 0.7921, Accuracy: 78/96 (81%)

Train Epoch: 37 [0/336 (0%)]	Loss: 0.057157
Train Epoch: 37	Average Loss: 0.056749	Accuracy: 100.00%


 25%|██▍       | 37/150 [02:36<09:07,  4.85s/it]


Test set: Average loss: 0.7933, Accuracy: 78/96 (81%)

Train Epoch: 38 [0/336 (0%)]	Loss: 0.053165
Train Epoch: 38	Average Loss: 0.058567	Accuracy: 100.00%


 25%|██▌       | 38/150 [02:41<09:01,  4.84s/it]


Test set: Average loss: 0.7953, Accuracy: 78/96 (81%)

Train Epoch: 39 [0/336 (0%)]	Loss: 0.067429
Train Epoch: 39	Average Loss: 0.052140	Accuracy: 100.00%


 26%|██▌       | 39/150 [02:46<08:59,  4.86s/it]


Test set: Average loss: 0.7965, Accuracy: 78/96 (81%)

Train Epoch: 40 [0/336 (0%)]	Loss: 0.057920
Train Epoch: 40	Average Loss: 0.057881	Accuracy: 100.00%


 27%|██▋       | 40/150 [02:51<08:52,  4.84s/it]


Test set: Average loss: 0.7970, Accuracy: 78/96 (81%)

Train Epoch: 41 [0/336 (0%)]	Loss: 0.058064
Train Epoch: 41	Average Loss: 0.055945	Accuracy: 100.00%


 27%|██▋       | 41/150 [02:55<08:50,  4.87s/it]


Test set: Average loss: 0.7977, Accuracy: 78/96 (81%)

Train Epoch: 42 [0/336 (0%)]	Loss: 0.044478
Train Epoch: 42	Average Loss: 0.056440	Accuracy: 100.00%


 28%|██▊       | 42/150 [03:00<08:43,  4.85s/it]


Test set: Average loss: 0.7984, Accuracy: 78/96 (81%)

Train Epoch: 43 [0/336 (0%)]	Loss: 0.082103
Train Epoch: 43	Average Loss: 0.051560	Accuracy: 100.00%


 29%|██▊       | 43/150 [03:05<08:37,  4.83s/it]


Test set: Average loss: 0.7990, Accuracy: 78/96 (81%)

Train Epoch: 44 [0/336 (0%)]	Loss: 0.051248
Train Epoch: 44	Average Loss: 0.058339	Accuracy: 100.00%


 29%|██▉       | 44/150 [03:10<08:37,  4.88s/it]


Test set: Average loss: 0.7998, Accuracy: 78/96 (81%)

Train Epoch: 45 [0/336 (0%)]	Loss: 0.054519
Train Epoch: 45	Average Loss: 0.051869	Accuracy: 100.00%


 30%|███       | 45/150 [03:15<08:25,  4.81s/it]


Test set: Average loss: 0.7999, Accuracy: 78/96 (81%)

Train Epoch: 46 [0/336 (0%)]	Loss: 0.054373
Train Epoch: 46	Average Loss: 0.053461	Accuracy: 100.00%


 31%|███       | 46/150 [03:20<08:20,  4.82s/it]


Test set: Average loss: 0.8002, Accuracy: 78/96 (81%)

Train Epoch: 47 [0/336 (0%)]	Loss: 0.053930
Train Epoch: 47	Average Loss: 0.055953	Accuracy: 100.00%


 31%|███▏      | 47/150 [03:24<08:19,  4.85s/it]


Test set: Average loss: 0.8004, Accuracy: 78/96 (81%)

Train Epoch: 48 [0/336 (0%)]	Loss: 0.048269
Train Epoch: 48	Average Loss: 0.056236	Accuracy: 100.00%


 32%|███▏      | 48/150 [03:29<08:09,  4.80s/it]


Test set: Average loss: 0.8007, Accuracy: 78/96 (81%)

Train Epoch: 49 [0/336 (0%)]	Loss: 0.065360
Train Epoch: 49	Average Loss: 0.051869	Accuracy: 100.00%


 33%|███▎      | 49/150 [03:34<08:12,  4.88s/it]


Test set: Average loss: 0.8007, Accuracy: 78/96 (81%)

Train Epoch: 50 [0/336 (0%)]	Loss: 0.056818
Train Epoch: 50	Average Loss: 0.050601	Accuracy: 100.00%


 33%|███▎      | 50/150 [03:39<08:13,  4.93s/it]


Test set: Average loss: 0.8008, Accuracy: 78/96 (81%)

Train Epoch: 51 [0/336 (0%)]	Loss: 0.044328
Train Epoch: 51	Average Loss: 0.055339	Accuracy: 100.00%


 34%|███▍      | 51/150 [03:44<08:09,  4.95s/it]


Test set: Average loss: 0.8008, Accuracy: 78/96 (81%)

Train Epoch: 52 [0/336 (0%)]	Loss: 0.050670
Train Epoch: 52	Average Loss: 0.053572	Accuracy: 100.00%


 35%|███▍      | 52/150 [03:49<07:59,  4.89s/it]


Test set: Average loss: 0.8010, Accuracy: 78/96 (81%)

Train Epoch: 53 [0/336 (0%)]	Loss: 0.043625
Train Epoch: 53	Average Loss: 0.057077	Accuracy: 100.00%


 35%|███▌      | 53/150 [03:54<07:49,  4.84s/it]


Test set: Average loss: 0.8011, Accuracy: 78/96 (81%)

Train Epoch: 54 [0/336 (0%)]	Loss: 0.035989
Train Epoch: 54	Average Loss: 0.051028	Accuracy: 100.00%


 36%|███▌      | 54/150 [03:59<07:47,  4.87s/it]


Test set: Average loss: 0.8012, Accuracy: 78/96 (81%)

Train Epoch: 55 [0/336 (0%)]	Loss: 0.068801
Train Epoch: 55	Average Loss: 0.055868	Accuracy: 100.00%


 37%|███▋      | 55/150 [04:04<07:43,  4.87s/it]


Test set: Average loss: 0.8014, Accuracy: 78/96 (81%)

Train Epoch: 56 [0/336 (0%)]	Loss: 0.049139
Train Epoch: 56	Average Loss: 0.054420	Accuracy: 100.00%


 37%|███▋      | 56/150 [04:08<07:36,  4.86s/it]


Test set: Average loss: 0.8014, Accuracy: 78/96 (81%)

Train Epoch: 57 [0/336 (0%)]	Loss: 0.046372
Train Epoch: 57	Average Loss: 0.052410	Accuracy: 100.00%


 38%|███▊      | 57/150 [04:13<07:27,  4.81s/it]


Test set: Average loss: 0.8014, Accuracy: 78/96 (81%)

Train Epoch: 58 [0/336 (0%)]	Loss: 0.068783
Train Epoch: 58	Average Loss: 0.049814	Accuracy: 100.00%


 39%|███▊      | 58/150 [04:18<07:28,  4.88s/it]


Test set: Average loss: 0.8015, Accuracy: 78/96 (81%)

Train Epoch: 59 [0/336 (0%)]	Loss: 0.044595
Train Epoch: 59	Average Loss: 0.051945	Accuracy: 100.00%


 39%|███▉      | 59/150 [04:23<07:22,  4.86s/it]


Test set: Average loss: 0.8016, Accuracy: 78/96 (81%)

Train Epoch: 60 [0/336 (0%)]	Loss: 0.043177
Train Epoch: 60	Average Loss: 0.063015	Accuracy: 100.00%


 40%|████      | 60/150 [04:28<07:16,  4.85s/it]


Test set: Average loss: 0.8017, Accuracy: 78/96 (81%)

Train Epoch: 61 [0/336 (0%)]	Loss: 0.054818
Train Epoch: 61	Average Loss: 0.051509	Accuracy: 100.00%


 41%|████      | 61/150 [04:33<07:13,  4.88s/it]


Test set: Average loss: 0.8018, Accuracy: 78/96 (81%)

Train Epoch: 62 [0/336 (0%)]	Loss: 0.067708
Train Epoch: 62	Average Loss: 0.051321	Accuracy: 100.00%


 41%|████▏     | 62/150 [04:38<07:13,  4.93s/it]


Test set: Average loss: 0.8018, Accuracy: 78/96 (81%)

Train Epoch: 63 [0/336 (0%)]	Loss: 0.043015
Train Epoch: 63	Average Loss: 0.052461	Accuracy: 100.00%


 42%|████▏     | 63/150 [04:43<07:09,  4.93s/it]


Test set: Average loss: 0.8019, Accuracy: 78/96 (81%)

Train Epoch: 64 [0/336 (0%)]	Loss: 0.032272
Train Epoch: 64	Average Loss: 0.050057	Accuracy: 100.00%


 43%|████▎     | 64/150 [04:47<06:56,  4.85s/it]


Test set: Average loss: 0.8020, Accuracy: 78/96 (81%)

Train Epoch: 65 [0/336 (0%)]	Loss: 0.065691
Train Epoch: 65	Average Loss: 0.054335	Accuracy: 100.00%


 43%|████▎     | 65/150 [04:52<06:45,  4.78s/it]


Test set: Average loss: 0.8020, Accuracy: 78/96 (81%)

Train Epoch: 66 [0/336 (0%)]	Loss: 0.034885
Train Epoch: 66	Average Loss: 0.058161	Accuracy: 100.00%


 44%|████▍     | 66/150 [04:57<06:38,  4.75s/it]


Test set: Average loss: 0.8021, Accuracy: 78/96 (81%)

Train Epoch: 67 [0/336 (0%)]	Loss: 0.064931
Train Epoch: 67	Average Loss: 0.054282	Accuracy: 100.00%


 45%|████▍     | 67/150 [05:02<06:40,  4.83s/it]


Test set: Average loss: 0.8021, Accuracy: 78/96 (81%)

Train Epoch: 68 [0/336 (0%)]	Loss: 0.069255
Train Epoch: 68	Average Loss: 0.050375	Accuracy: 100.00%


 45%|████▌     | 68/150 [05:06<06:31,  4.78s/it]


Test set: Average loss: 0.8021, Accuracy: 78/96 (81%)

Train Epoch: 69 [0/336 (0%)]	Loss: 0.064045
Train Epoch: 69	Average Loss: 0.050758	Accuracy: 100.00%


 46%|████▌     | 69/150 [05:11<06:24,  4.75s/it]


Test set: Average loss: 0.8021, Accuracy: 78/96 (81%)

Train Epoch: 70 [0/336 (0%)]	Loss: 0.052604
Train Epoch: 70	Average Loss: 0.050169	Accuracy: 100.00%


 47%|████▋     | 70/150 [05:16<06:15,  4.69s/it]


Test set: Average loss: 0.8022, Accuracy: 78/96 (81%)

Train Epoch: 71 [0/336 (0%)]	Loss: 0.058316
Train Epoch: 71	Average Loss: 0.053580	Accuracy: 100.00%


 47%|████▋     | 71/150 [05:20<06:11,  4.70s/it]


Test set: Average loss: 0.8022, Accuracy: 78/96 (81%)

Train Epoch: 72 [0/336 (0%)]	Loss: 0.041828
Train Epoch: 72	Average Loss: 0.049934	Accuracy: 100.00%


 48%|████▊     | 72/150 [05:25<06:04,  4.67s/it]


Test set: Average loss: 0.8022, Accuracy: 78/96 (81%)

Train Epoch: 73 [0/336 (0%)]	Loss: 0.058738
Train Epoch: 73	Average Loss: 0.051201	Accuracy: 100.00%


 49%|████▊     | 73/150 [05:30<06:08,  4.78s/it]


Test set: Average loss: 0.8022, Accuracy: 78/96 (81%)

Train Epoch: 74 [0/336 (0%)]	Loss: 0.048654
Train Epoch: 74	Average Loss: 0.054032	Accuracy: 100.00%


 49%|████▉     | 74/150 [05:34<05:56,  4.70s/it]


Test set: Average loss: 0.8022, Accuracy: 78/96 (81%)

Train Epoch: 75 [0/336 (0%)]	Loss: 0.066189
Train Epoch: 75	Average Loss: 0.049692	Accuracy: 100.00%


 50%|█████     | 75/150 [05:39<05:55,  4.74s/it]


Test set: Average loss: 0.8022, Accuracy: 78/96 (81%)

Train Epoch: 76 [0/336 (0%)]	Loss: 0.061904
Train Epoch: 76	Average Loss: 0.048790	Accuracy: 100.00%


 51%|█████     | 76/150 [05:44<05:48,  4.71s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 77 [0/336 (0%)]	Loss: 0.081038
Train Epoch: 77	Average Loss: 0.048754	Accuracy: 100.00%


 51%|█████▏    | 77/150 [05:49<05:42,  4.70s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 78 [0/336 (0%)]	Loss: 0.052005
Train Epoch: 78	Average Loss: 0.054557	Accuracy: 100.00%


 52%|█████▏    | 78/150 [05:53<05:35,  4.66s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 79 [0/336 (0%)]	Loss: 0.065956
Train Epoch: 79	Average Loss: 0.049672	Accuracy: 100.00%


 53%|█████▎    | 79/150 [05:58<05:35,  4.72s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 80 [0/336 (0%)]	Loss: 0.043726
Train Epoch: 80	Average Loss: 0.054293	Accuracy: 100.00%


 53%|█████▎    | 80/150 [06:03<05:33,  4.77s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 81 [0/336 (0%)]	Loss: 0.056045
Train Epoch: 81	Average Loss: 0.055703	Accuracy: 100.00%


 54%|█████▍    | 81/150 [06:08<05:28,  4.76s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 82 [0/336 (0%)]	Loss: 0.048927
Train Epoch: 82	Average Loss: 0.047886	Accuracy: 100.00%


 55%|█████▍    | 82/150 [06:12<05:17,  4.66s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 83 [0/336 (0%)]	Loss: 0.049236
Train Epoch: 83	Average Loss: 0.061209	Accuracy: 100.00%


 55%|█████▌    | 83/150 [06:16<04:55,  4.42s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 84 [0/336 (0%)]	Loss: 0.047571
Train Epoch: 84	Average Loss: 0.052503	Accuracy: 100.00%


 56%|█████▌    | 84/150 [06:20<04:42,  4.28s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 85 [0/336 (0%)]	Loss: 0.042316
Train Epoch: 85	Average Loss: 0.054843	Accuracy: 100.00%


 57%|█████▋    | 85/150 [06:24<04:31,  4.18s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 86 [0/336 (0%)]	Loss: 0.066421
Train Epoch: 86	Average Loss: 0.054116	Accuracy: 100.00%


 57%|█████▋    | 86/150 [06:28<04:31,  4.25s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 87 [0/336 (0%)]	Loss: 0.057561
Train Epoch: 87	Average Loss: 0.051483	Accuracy: 100.00%


 58%|█████▊    | 87/150 [06:32<04:22,  4.17s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 88 [0/336 (0%)]	Loss: 0.045477
Train Epoch: 88	Average Loss: 0.054755	Accuracy: 100.00%


 59%|█████▊    | 88/150 [06:36<04:11,  4.06s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 89 [0/336 (0%)]	Loss: 0.034342
Train Epoch: 89	Average Loss: 0.059162	Accuracy: 100.00%


 59%|█████▉    | 89/150 [06:40<04:06,  4.04s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 90 [0/336 (0%)]	Loss: 0.044423
Train Epoch: 90	Average Loss: 0.052750	Accuracy: 100.00%


 60%|██████    | 90/150 [06:44<04:09,  4.15s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 91 [0/336 (0%)]	Loss: 0.053988
Train Epoch: 91	Average Loss: 0.054546	Accuracy: 100.00%


 61%|██████    | 91/150 [06:50<04:30,  4.58s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 92 [0/336 (0%)]	Loss: 0.064836
Train Epoch: 92	Average Loss: 0.051591	Accuracy: 100.00%


 61%|██████▏   | 92/150 [06:56<04:51,  5.03s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 93 [0/336 (0%)]	Loss: 0.050407
Train Epoch: 93	Average Loss: 0.051936	Accuracy: 100.00%


 62%|██████▏   | 93/150 [07:02<04:54,  5.16s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 94 [0/336 (0%)]	Loss: 0.046054
Train Epoch: 94	Average Loss: 0.051233	Accuracy: 100.00%


 63%|██████▎   | 94/150 [07:05<04:25,  4.74s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 95 [0/336 (0%)]	Loss: 0.049022
Train Epoch: 95	Average Loss: 0.056751	Accuracy: 100.00%


 63%|██████▎   | 95/150 [07:09<04:10,  4.56s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 96 [0/336 (0%)]	Loss: 0.048156
Train Epoch: 96	Average Loss: 0.053565	Accuracy: 100.00%


 64%|██████▍   | 96/150 [07:13<03:53,  4.32s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 97 [0/336 (0%)]	Loss: 0.045238
Train Epoch: 97	Average Loss: 0.057920	Accuracy: 100.00%


 65%|██████▍   | 97/150 [07:17<03:42,  4.19s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 98 [0/336 (0%)]	Loss: 0.053283
Train Epoch: 98	Average Loss: 0.049912	Accuracy: 100.00%


 65%|██████▌   | 98/150 [07:21<03:33,  4.10s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 99 [0/336 (0%)]	Loss: 0.044348
Train Epoch: 99	Average Loss: 0.053789	Accuracy: 100.00%


 66%|██████▌   | 99/150 [07:25<03:31,  4.14s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 100 [0/336 (0%)]	Loss: 0.079535
Train Epoch: 100	Average Loss: 0.053807	Accuracy: 100.00%


 67%|██████▋   | 100/150 [07:29<03:23,  4.08s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 101 [0/336 (0%)]	Loss: 0.054667
Train Epoch: 101	Average Loss: 0.052685	Accuracy: 100.00%


 67%|██████▋   | 101/150 [07:33<03:19,  4.07s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 102 [0/336 (0%)]	Loss: 0.072702
Train Epoch: 102	Average Loss: 0.049983	Accuracy: 100.00%


 68%|██████▊   | 102/150 [07:37<03:17,  4.11s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 103 [0/336 (0%)]	Loss: 0.046339
Train Epoch: 103	Average Loss: 0.048417	Accuracy: 100.00%


 69%|██████▊   | 103/150 [07:42<03:17,  4.19s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 104 [0/336 (0%)]	Loss: 0.062177
Train Epoch: 104	Average Loss: 0.049143	Accuracy: 100.00%


 69%|██████▉   | 104/150 [07:46<03:15,  4.25s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 105 [0/336 (0%)]	Loss: 0.052004
Train Epoch: 105	Average Loss: 0.051991	Accuracy: 100.00%


 70%|███████   | 105/150 [07:50<03:07,  4.17s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 106 [0/336 (0%)]	Loss: 0.079809
Train Epoch: 106	Average Loss: 0.052406	Accuracy: 100.00%


 71%|███████   | 106/150 [07:54<02:59,  4.07s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 107 [0/336 (0%)]	Loss: 0.080838
Train Epoch: 107	Average Loss: 0.050911	Accuracy: 100.00%


 71%|███████▏  | 107/150 [07:58<02:55,  4.07s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 108 [0/336 (0%)]	Loss: 0.060939
Train Epoch: 108	Average Loss: 0.049018	Accuracy: 100.00%


 72%|███████▏  | 108/150 [08:02<02:48,  4.02s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 109 [0/336 (0%)]	Loss: 0.059576
Train Epoch: 109	Average Loss: 0.055646	Accuracy: 100.00%


 73%|███████▎  | 109/150 [08:06<02:41,  3.94s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 110 [0/336 (0%)]	Loss: 0.042338
Train Epoch: 110	Average Loss: 0.051037	Accuracy: 100.00%


 73%|███████▎  | 110/150 [08:09<02:35,  3.89s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 111 [0/336 (0%)]	Loss: 0.073347
Train Epoch: 111	Average Loss: 0.050222	Accuracy: 100.00%


 74%|███████▍  | 111/150 [08:14<02:35,  4.00s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 112 [0/336 (0%)]	Loss: 0.043888
Train Epoch: 112	Average Loss: 0.055426	Accuracy: 100.00%


 75%|███████▍  | 112/150 [08:18<02:35,  4.09s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 113 [0/336 (0%)]	Loss: 0.063261
Train Epoch: 113	Average Loss: 0.050688	Accuracy: 100.00%


 75%|███████▌  | 113/150 [08:22<02:32,  4.13s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 114 [0/336 (0%)]	Loss: 0.058120
Train Epoch: 114	Average Loss: 0.050737	Accuracy: 100.00%


 76%|███████▌  | 114/150 [08:27<02:30,  4.18s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 115 [0/336 (0%)]	Loss: 0.055928
Train Epoch: 115	Average Loss: 0.052288	Accuracy: 100.00%


 77%|███████▋  | 115/150 [08:31<02:32,  4.37s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 116 [0/336 (0%)]	Loss: 0.049100
Train Epoch: 116	Average Loss: 0.048956	Accuracy: 100.00%


 77%|███████▋  | 116/150 [08:35<02:24,  4.24s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 117 [0/336 (0%)]	Loss: 0.071595
Train Epoch: 117	Average Loss: 0.050357	Accuracy: 100.00%


 78%|███████▊  | 117/150 [08:39<02:19,  4.22s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 118 [0/336 (0%)]	Loss: 0.054503
Train Epoch: 118	Average Loss: 0.052208	Accuracy: 100.00%


 79%|███████▊  | 118/150 [08:44<02:16,  4.26s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 119 [0/336 (0%)]	Loss: 0.052382
Train Epoch: 119	Average Loss: 0.053708	Accuracy: 100.00%


 79%|███████▉  | 119/150 [08:48<02:08,  4.13s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 120 [0/336 (0%)]	Loss: 0.043349
Train Epoch: 120	Average Loss: 0.052022	Accuracy: 100.00%


 80%|████████  | 120/150 [08:52<02:02,  4.10s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 121 [0/336 (0%)]	Loss: 0.030407
Train Epoch: 121	Average Loss: 0.052260	Accuracy: 100.00%


 81%|████████  | 121/150 [08:56<01:59,  4.13s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 122 [0/336 (0%)]	Loss: 0.061308
Train Epoch: 122	Average Loss: 0.049606	Accuracy: 100.00%


 81%|████████▏ | 122/150 [09:01<01:59,  4.28s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 123 [0/336 (0%)]	Loss: 0.045277
Train Epoch: 123	Average Loss: 0.056549	Accuracy: 100.00%


 82%|████████▏ | 123/150 [09:05<01:55,  4.28s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 124 [0/336 (0%)]	Loss: 0.062437
Train Epoch: 124	Average Loss: 0.058585	Accuracy: 100.00%


 83%|████████▎ | 124/150 [09:09<01:50,  4.26s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 125 [0/336 (0%)]	Loss: 0.055362
Train Epoch: 125	Average Loss: 0.049734	Accuracy: 100.00%


 83%|████████▎ | 125/150 [09:13<01:47,  4.29s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 126 [0/336 (0%)]	Loss: 0.049470
Train Epoch: 126	Average Loss: 0.051214	Accuracy: 100.00%


 84%|████████▍ | 126/150 [09:18<01:44,  4.36s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 127 [0/336 (0%)]	Loss: 0.046916
Train Epoch: 127	Average Loss: 0.049546	Accuracy: 100.00%


 85%|████████▍ | 127/150 [09:22<01:40,  4.37s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 128 [0/336 (0%)]	Loss: 0.066133
Train Epoch: 128	Average Loss: 0.051445	Accuracy: 100.00%


 85%|████████▌ | 128/150 [09:27<01:38,  4.47s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 129 [0/336 (0%)]	Loss: 0.067151
Train Epoch: 129	Average Loss: 0.055239	Accuracy: 100.00%


 86%|████████▌ | 129/150 [09:31<01:30,  4.31s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 130 [0/336 (0%)]	Loss: 0.065426
Train Epoch: 130	Average Loss: 0.050258	Accuracy: 100.00%


 87%|████████▋ | 130/150 [09:35<01:23,  4.17s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 131 [0/336 (0%)]	Loss: 0.076480
Train Epoch: 131	Average Loss: 0.049631	Accuracy: 100.00%


 87%|████████▋ | 131/150 [09:39<01:20,  4.26s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 132 [0/336 (0%)]	Loss: 0.067752
Train Epoch: 132	Average Loss: 0.055605	Accuracy: 100.00%


 88%|████████▊ | 132/150 [09:43<01:16,  4.26s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 133 [0/336 (0%)]	Loss: 0.048282
Train Epoch: 133	Average Loss: 0.056000	Accuracy: 100.00%


 89%|████████▊ | 133/150 [09:48<01:12,  4.27s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 134 [0/336 (0%)]	Loss: 0.067529
Train Epoch: 134	Average Loss: 0.052834	Accuracy: 100.00%


 89%|████████▉ | 134/150 [09:52<01:09,  4.36s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 135 [0/336 (0%)]	Loss: 0.056603
Train Epoch: 135	Average Loss: 0.053444	Accuracy: 100.00%


 90%|█████████ | 135/150 [09:57<01:06,  4.46s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 136 [0/336 (0%)]	Loss: 0.054868
Train Epoch: 136	Average Loss: 0.053761	Accuracy: 100.00%


 91%|█████████ | 136/150 [10:01<01:00,  4.35s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 137 [0/336 (0%)]	Loss: 0.060009
Train Epoch: 137	Average Loss: 0.050561	Accuracy: 100.00%


 91%|█████████▏| 137/150 [10:05<00:56,  4.34s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 138 [0/336 (0%)]	Loss: 0.039604
Train Epoch: 138	Average Loss: 0.057238	Accuracy: 100.00%


 92%|█████████▏| 138/150 [10:10<00:52,  4.34s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 139 [0/336 (0%)]	Loss: 0.054147
Train Epoch: 139	Average Loss: 0.052673	Accuracy: 100.00%


 93%|█████████▎| 139/150 [10:14<00:48,  4.43s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 140 [0/336 (0%)]	Loss: 0.059599
Train Epoch: 140	Average Loss: 0.056502	Accuracy: 100.00%


 93%|█████████▎| 140/150 [10:19<00:43,  4.37s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 141 [0/336 (0%)]	Loss: 0.046274
Train Epoch: 141	Average Loss: 0.053148	Accuracy: 100.00%


 94%|█████████▍| 141/150 [10:23<00:38,  4.30s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 142 [0/336 (0%)]	Loss: 0.050175
Train Epoch: 142	Average Loss: 0.050509	Accuracy: 100.00%


 95%|█████████▍| 142/150 [10:27<00:34,  4.31s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 143 [0/336 (0%)]	Loss: 0.050664
Train Epoch: 143	Average Loss: 0.050708	Accuracy: 100.00%


 95%|█████████▌| 143/150 [10:31<00:29,  4.27s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 144 [0/336 (0%)]	Loss: 0.054876
Train Epoch: 144	Average Loss: 0.054044	Accuracy: 100.00%


 96%|█████████▌| 144/150 [10:36<00:25,  4.32s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 145 [0/336 (0%)]	Loss: 0.061374
Train Epoch: 145	Average Loss: 0.054870	Accuracy: 100.00%


 97%|█████████▋| 145/150 [10:40<00:21,  4.30s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 146 [0/336 (0%)]	Loss: 0.064989
Train Epoch: 146	Average Loss: 0.051243	Accuracy: 100.00%


 97%|█████████▋| 146/150 [10:45<00:17,  4.39s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 147 [0/336 (0%)]	Loss: 0.067254
Train Epoch: 147	Average Loss: 0.050502	Accuracy: 100.00%


 98%|█████████▊| 147/150 [10:50<00:13,  4.56s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 148 [0/336 (0%)]	Loss: 0.063089
Train Epoch: 148	Average Loss: 0.050249	Accuracy: 100.00%


 99%|█████████▊| 148/150 [10:54<00:09,  4.56s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 149 [0/336 (0%)]	Loss: 0.072655
Train Epoch: 149	Average Loss: 0.052845	Accuracy: 100.00%


 99%|█████████▉| 149/150 [10:58<00:04,  4.49s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)

Train Epoch: 150 [0/336 (0%)]	Loss: 0.050512
Train Epoch: 150	Average Loss: 0.054352	Accuracy: 100.00%


100%|██████████| 150/150 [11:03<00:00,  4.42s/it]


Test set: Average loss: 0.8023, Accuracy: 78/96 (81%)



In [47]:
from sklearn.metrics import classification_report

# Assuming the testing loop code here

# After the testing loop
report = classification_report(all_targets, all_preds, target_names=['start', 'stop', 'home', 'pick_up', 'approach', 'free'])  # Adjust target_names based on your dataset
print(report)
from sklearn.metrics import confusion_matrix

confision_matrix = confusion_matrix(all_targets, all_preds)
print(confision_matrix)

              precision    recall  f1-score   support

       start       0.75      0.88      0.81      1800
        stop       0.70      0.61      0.65      3300
        home       0.71      0.71      0.71      2250
     pick_up       0.86      0.76      0.81      2850
    approach       0.79      0.99      0.88      2100
        free       0.94      0.89      0.92      2100

    accuracy                           0.79     14400
   macro avg       0.79      0.81      0.79     14400
weighted avg       0.79      0.79      0.78     14400

[[1584  148    7   37    7   17]
 [ 307 2007  469  309  182   26]
 [ 163  430 1598    6   16   37]
 [  33  293   10 2173  314   27]
 [   6    2    9    0 2070   13]
 [  19    4  163    0   37 1877]]


In [51]:
class SimplifiedWaveNet(nn.Module):
    def __init__(self, num_classes, num_channels=1, num_layers=4, num_filters=8, dilation_rates=None):
        super(SimplifiedWaveNet, self).__init__()
        self.num_layers = num_layers
        
        self.init_conv = nn.Conv1d(num_channels, num_filters, kernel_size=1)

        self.conv1 = nn.Conv1d(num_filters, num_filters * 2, kernel_size=3, padding=1, dilation=2)
        self.conv2 = nn.Conv1d(num_filters * 2, num_filters * 4, kernel_size=3, padding=2, dilation=4)
        self.conv3 = nn.Conv1d(num_filters * 4, num_filters * 8, kernel_size=3, padding=4, dilation=8)
        self.conv4 = nn.Conv1d(num_filters * 8, num_filters * 16, kernel_size=3, padding=8, dilation=16)

        self.pool = nn.MaxPool1d(4)

        self.final_conv = nn.Conv1d(256, 128, kernel_size=1)
        self.linear = nn.Linear(128 * 57 * 1, 256)
        self.linear2 = nn.Linear(256, num_classes)

    def forward(self, x):
        x = self.init_conv(x)
        x1 = self.pool(F.relu(self.conv1(x)))
        x2 = self.pool(F.relu(self.conv2(x1)))
        x3 = self.pool(F.relu(self.conv3(x2)))
        x4 = self.pool(F.relu(self.conv4(x3)))
        x5 = self.final_conv(x4)
        # print(x4.shape)
        x5 = x5.view(x5.size(0), -1)
        x6 = F.relu(self.linear(x5))
        x7 = self.linear2(x6)
        return x7



def get_simplified_wavenet(num_classes, num_channels=1, num_layers=3, num_filters=16, dilation_rates=None, device='cpu'):
    model = SimplifiedWaveNet(num_classes, num_channels, num_layers, num_filters, dilation_rates)
    return model.to(device)

model=get_simplified_wavenet(6)
print(model)

SimplifiedWaveNet(
  (init_conv): Conv1d(1, 16, kernel_size=(1,), stride=(1,))
  (conv1): Conv1d(16, 32, kernel_size=(3,), stride=(1,), padding=(1,), dilation=(2,))
  (conv2): Conv1d(32, 64, kernel_size=(3,), stride=(1,), padding=(2,), dilation=(4,))
  (conv3): Conv1d(64, 128, kernel_size=(3,), stride=(1,), padding=(4,), dilation=(8,))
  (conv4): Conv1d(128, 256, kernel_size=(3,), stride=(1,), padding=(8,), dilation=(16,))
  (pool): MaxPool1d(kernel_size=4, stride=4, padding=0, dilation=1, ceil_mode=False)
  (final_conv): Conv1d(256, 128, kernel_size=(1,), stride=(1,))
  (linear): Linear(in_features=7296, out_features=256, bias=True)
  (linear2): Linear(in_features=256, out_features=6, bias=True)
)


In [48]:
import torch
import pandas as pd
from torch.utils.data import Dataset
import os
import torchaudio

class My_Dataset(Dataset):
    def __init__(self, csv_file, root_dir, set_number):
        self.data = pd.read_csv(csv_file)
        self.root_dir = root_dir
        self.set_number = set_number
        self.filtered_indices = self.filter()

    def __len__(self):
        return len(self.filtered_indices)

    def filter(self):
        filtered_indices = []
        for idx in range(len(self.data)):
            set_value = int(self.data.iloc[idx, 1])
            if set_value == self.set_number:
                filtered_indices.append(idx)
        return filtered_indices

    def __getitem__(self, idx):
        idx = self.filtered_indices[idx]
        file = os.path.join(self.root_dir, self.data.iloc[idx, 0])
        # class_label = int(self.data.iloc[idx, 2])
        speaker_id = int(self.data.iloc[idx, 3])
        waveform, _ = torchaudio.load(file)
        # Normalize the waveform
        waveform = (waveform - waveform.mean()) / waveform.std()
        # if waveform.shape[0] != num_input_channels:
        #     waveform = waveform.repeat(num_input_channels // waveform.shape[0], 1)
        return waveform, speaker_id

csv_file = 'dataset.csv'
root_dir = 'Inregistrari'
num_input_channels = 128  # Ensure this matches the expected input channels for the model

train_dataset = My_Dataset(csv_file, root_dir, 0)
test_dataset = My_Dataset(csv_file, root_dir, 1)
valid_dataset = My_Dataset(csv_file, root_dir, 2)



import torch.nn as nn
import torch.nn.functional as F

class SimplifiedWaveNet(nn.Module):
    def __init__(self, num_classes, num_channels=1, num_layers=4, num_filters=8, dilation_rates=None):
        super(SimplifiedWaveNet, self).__init__()
        self.num_layers = num_layers
        
        self.init_conv = nn.Conv1d(num_channels, num_filters, kernel_size=1)

        self.conv1 = nn.Conv1d(num_filters, num_filters * 2, kernel_size=3, padding=1, dilation=2)
        self.conv2 = nn.Conv1d(num_filters * 2, num_filters * 4, kernel_size=3, padding=2, dilation=4)
        self.conv3 = nn.Conv1d(num_filters * 4, num_filters * 8, kernel_size=3, padding=4, dilation=8)
        self.conv4 = nn.Conv1d(num_filters * 8, num_filters * 16, kernel_size=3, padding=8, dilation=16)

        self.pool = nn.MaxPool1d(4)

        self.final_conv = nn.Conv1d(256, 128, kernel_size=1)
        self.linear = nn.Linear(128 * 57 * 1, 256)
        self.linear2 = nn.Linear(256, num_classes)

    def forward(self, x):
        x = self.init_conv(x)
        x1 = self.pool(F.relu(self.conv1(x)))
        x2 = self.pool(F.relu(self.conv2(x1)))
        x3 = self.pool(F.relu(self.conv3(x2)))
        x4 = self.pool(F.relu(self.conv4(x3)))
        x5 = self.final_conv(x4)
        # print(x4.shape)
        x5 = x5.view(x5.size(0), -1)
        x6 = F.relu(self.linear(x5))
        x7 = self.linear2(x6)
        return x7



def get_simplified_wavenet(num_classes, num_channels=1, num_layers=3, num_filters=16, dilation_rates=None, device='cpu'):
    model = SimplifiedWaveNet(num_classes, num_channels, num_layers, num_filters, dilation_rates)
    return model.to(device)

model=get_simplified_wavenet(8)



#print the number of trainable parameters
def count_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)

nr = count_parameters(model)
print(f'The model has {nr:,} trainable parameters')
num_input_channels = 128  # Adju


import torch.optim as optim
from torch.utils.data import DataLoader
from tqdm import tqdm

batch_size = 64
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=0, pin_memory=True)
valid_loader = DataLoader(valid_dataset, batch_size=batch_size, shuffle=False, num_workers=0, pin_memory=True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=0, pin_memory=True)

    

optimizer = optim.Adam(model.parameters(), lr=0.001)  # Increased learning rate
criterion = nn.CrossEntropyLoss()

train_losses = []
train_accuracies = []
test_losses = []
test_accuracies = []
all_preds = []
all_targets = []

def train(model, device, train_loader, optimizer, epoch, log_interval, scheduler):
    model.train()
    running_loss = 0.0
    correct = 0
    for batch_idx, (data, target) in enumerate(train_loader):
        data, target = data.to(device), target.to(device)
        optimizer.zero_grad()
        # data = data.squeeze(1)  # Remove channel dimension

        # print(data.shape, target.shape)


        output = model(data)
        loss = criterion(output, target)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()
        pred = output.argmax(dim=1, keepdim=True)
        correct += pred.eq(target.view_as(pred)).sum().item()
        if batch_idx % log_interval == 0:
            print(f'Train Epoch: {epoch} [{batch_idx * len(data)}/{len(train_loader.dataset)} ({100. * batch_idx / len(train_loader):.0f}%)]\tLoss: {loss.item():.6f}')
    avg_loss = running_loss / len(train_loader)
    accuracy = 100. * correct / len(train_loader.dataset)
    train_losses.append(avg_loss)
    train_accuracies.append(accuracy)
    scheduler.step()
    print(f'Train Epoch: {epoch}\tAverage Loss: {avg_loss:.6f}\tAccuracy: {accuracy:.2f}%')


n_epoch = 150
log_interval = 20

scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=10, gamma=0.5)

with tqdm(total=n_epoch) as pbar:
    for epoch in range(1, n_epoch + 1):
        train(model, device, train_loader, optimizer, epoch, log_interval, scheduler)
        test(model, device, test_loader)
        torch.save(model.state_dict(), 'wavenet_command.pt')
        scheduler.step()  # Update the learning rate
        pbar.update(1)



Train Epoch: 138 [0/336 (0%)]	Loss: 0.237979
Train Epoch: 138	Average Loss: 0.178298	Accuracy: 96.13%


 92%|█████████▏| 138/150 [10:27<00:52,  4.34s/it]


Test set: Average loss: 0.9582, Accuracy: 75/96 (78%)

Train Epoch: 139 [0/336 (0%)]	Loss: 0.171575
Train Epoch: 139	Average Loss: 0.180616	Accuracy: 96.13%


 93%|█████████▎| 139/150 [10:31<00:49,  4.50s/it]


Test set: Average loss: 0.9582, Accuracy: 75/96 (78%)

Train Epoch: 140 [0/336 (0%)]	Loss: 0.168538
Train Epoch: 140	Average Loss: 0.171533	Accuracy: 96.13%


 93%|█████████▎| 140/150 [10:36<00:45,  4.56s/it]


Test set: Average loss: 0.9582, Accuracy: 75/96 (78%)

Train Epoch: 141 [0/336 (0%)]	Loss: 0.200474
Train Epoch: 141	Average Loss: 0.172438	Accuracy: 96.13%


 94%|█████████▍| 141/150 [10:41<00:41,  4.66s/it]


Test set: Average loss: 0.9582, Accuracy: 75/96 (78%)

Train Epoch: 142 [0/336 (0%)]	Loss: 0.242362
Train Epoch: 142	Average Loss: 0.188591	Accuracy: 96.13%


 95%|█████████▍| 142/150 [10:46<00:38,  4.83s/it]


Test set: Average loss: 0.9582, Accuracy: 75/96 (78%)

Train Epoch: 143 [0/336 (0%)]	Loss: 0.174322
Train Epoch: 143	Average Loss: 0.181565	Accuracy: 96.13%


 95%|█████████▌| 143/150 [10:52<00:35,  5.00s/it]


Test set: Average loss: 0.9582, Accuracy: 75/96 (78%)

Train Epoch: 144 [0/336 (0%)]	Loss: 0.177297
Train Epoch: 144	Average Loss: 0.184224	Accuracy: 96.13%


 96%|█████████▌| 144/150 [10:57<00:29,  5.00s/it]


Test set: Average loss: 0.9582, Accuracy: 75/96 (78%)

Train Epoch: 145 [0/336 (0%)]	Loss: 0.167013
Train Epoch: 145	Average Loss: 0.185636	Accuracy: 96.13%


 97%|█████████▋| 145/150 [11:02<00:25,  5.00s/it]


Test set: Average loss: 0.9582, Accuracy: 75/96 (78%)

Train Epoch: 146 [0/336 (0%)]	Loss: 0.218321
Train Epoch: 146	Average Loss: 0.177817	Accuracy: 96.13%


 97%|█████████▋| 146/150 [11:07<00:20,  5.05s/it]


Test set: Average loss: 0.9582, Accuracy: 75/96 (78%)

Train Epoch: 147 [0/336 (0%)]	Loss: 0.182773
Train Epoch: 147	Average Loss: 0.189002	Accuracy: 96.13%


 98%|█████████▊| 147/150 [11:12<00:15,  5.04s/it]


Test set: Average loss: 0.9582, Accuracy: 75/96 (78%)

Train Epoch: 148 [0/336 (0%)]	Loss: 0.206035
Train Epoch: 148	Average Loss: 0.166547	Accuracy: 96.13%


 99%|█████████▊| 148/150 [11:17<00:10,  5.14s/it]


Test set: Average loss: 0.9582, Accuracy: 75/96 (78%)

Train Epoch: 149 [0/336 (0%)]	Loss: 0.163532
Train Epoch: 149	Average Loss: 0.172698	Accuracy: 96.13%


 99%|█████████▉| 149/150 [11:22<00:05,  5.00s/it]


Test set: Average loss: 0.9582, Accuracy: 75/96 (78%)

Train Epoch: 150 [0/336 (0%)]	Loss: 0.130939
Train Epoch: 150	Average Loss: 0.202732	Accuracy: 96.13%


100%|██████████| 150/150 [11:26<00:00,  4.58s/it]


Test set: Average loss: 0.9582, Accuracy: 75/96 (78%)



In [50]:
from sklearn.metrics import classification_report

# Assuming the testing loop code here

# After the testing loop
report = classification_report(all_targets, all_preds, target_names=['Anca', 'Adi', 'Bobo', 'Danila', 'Mada', 'Toni', 'Oana', 'Luci'])  # Adjust target_names based on your dataset
print(report)
from sklearn.metrics import confusion_matrix

confision_matrix = confusion_matrix(all_targets, all_preds)
print(confision_matrix)

              precision    recall  f1-score   support

        Anca       0.76      0.96      0.85      1350
         Adi       0.85      0.87      0.86      1500
        Bobo       0.83      0.87      0.85      1800
      Danila       0.66      0.63      0.65      2250
        Mada       0.75      0.72      0.73      1650
        Toni       0.94      0.73      0.82      1950
        Oana       0.69      0.64      0.66      1800
        Luci       0.58      0.65      0.61      2100

    accuracy                           0.74     14400
   macro avg       0.76      0.76      0.75     14400
weighted avg       0.75      0.74      0.74     14400

[[1293    7    5   22    1   16    6    0]
 [  19 1301    0   16    0   28    0  136]
 [   6  158 1571   13   42    1    9    0]
 [  32   14    7 1428  188   14   41  526]
 [   7    1  164  150 1182    0  146    0]
 [ 176   14  127  175    0 1427    8   23]
 [  11    1    9  183  140   15 1153  288]
 [ 155   40    8  184   16   24  313 1360]]
